server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Esto asegura que Nginx redirija siempre a index.html
    # en lugar de dar error 404 cuando navegas por una SPA de Angular
    location / {
        try_files $uri $uri/ /index.html;
    }
}
